# Generated by Django 4.2.23 on 2025-07-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('description_image', models.ImageField(upload_to='descriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
