# Generated by Django 4.2.23 on 2025-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='lineup',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='performance_times',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='runtime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
