# Generated by Django 4.2.23 on 2025-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muze', '0002_concert_lineup_concert_performance_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
