# Generated by Django 4.2.23 on 2025-07-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muze', '0004_userprofile_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='parkjunhee', max_length=100),
            preserve_default=False,
        ),
    ]
