# Generated by Django 4.2.23 on 2025-08-08 09:48

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(default=2, upload_to=board.models.UploadToPathAndRename('uploads/')),
            preserve_default=False,
        ),
    ]
