# Generated by Django 4.2.23 on 2025-08-17 22:32

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=board.models.UploadToPathAndRename('uploads/')),
        ),
    ]
